name: Sync to S3

on:
  push:
    paths:
      - 'DaveBucket/**'
    branches:
      - main

jobs:
  sync-to-s3:
    runs-on: ubuntu-latest
    
    permissions:
      id-token: write
      contents: read
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install boto3
          
      - name: Run deployment script
        env:
          S3_BUCKET: ${{ secrets.S3_BUCKET_NAME }}
        run: python DeploymentScripts/deploy_to_s3.py